[project]
name = "10-000"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gitingest>=0.3.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "torch>=2.10.0",
]
